export const employees = [
  {
    ID: 1,
    Head_ID: 0,
    Full_Name: 'John Heart',
    Prefix: 'Mr.',
    Title: 'Tan Nguyen',
  },
  {
    ID: 2,
    Head_ID: 0,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'VIET BIM JSC',
  },
  {
    ID: 3,
    Head_ID: 1,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: "Tan's First Project",
  },
  {
    ID: 4,
    Head_ID: 1,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Demo Project',
  },
  {
    ID: 5,
    Head_ID: 3,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'A',
  },
  {
    ID: 6,
    Head_ID: 3,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'B',
  },
  {
    ID: 7,
    Head_ID: 3,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'C',
  },
  {
    ID: 8,
    Head_ID: 4,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: '1',
  },
  {
    ID: 9,
    Head_ID: 4,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: '2',
  },
  {
    ID: 10,
    Head_ID: 4,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: '3',
  },
  {
    ID: 11,
    Head_ID: 4,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: '4',
  },
  {
    ID: 12,
    Head_ID: 4,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: '5',
  },
  {
    ID: 13,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'VINSCHOOL',
  },
  {
    ID: 14,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Hầm B3-CT1 PK3 VINCITY OCEAN PARK',
  },
  {
    ID: 15,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Ecoland Duy Tân',
  },
  {
    ID: 16,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Toà L3 PK04 VINCITY OCEAN PARK',
  },
  {
    ID: 17,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Vincom Mĩ Tho',
  },
  {
    ID: 18,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Viet Bim_Phat Trien',
  },
  {
    ID: 19,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'P3 OCEAN PARK',
  },
  {
    ID: 20,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'L2 GRAND PARK',
  },
  {
    ID: 21,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Melinh Plaza Thanh Hoá',
  },
  {
    ID: 22,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Nhà Máy EUROWINDOW-KCNQuang Minh',
  },
  {
    ID: 23,
    Head_ID: 2,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'T26 TIME CITY',
  },
  {
    ID: 24,
    Head_ID: 13,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Q',
  },
  {
    ID: 25,
    Head_ID: 13,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'W',
  },
  {
    ID: 29,
    Head_ID: 14,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'a',
  },
  {
    ID: 26,
    Head_ID: 15,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Plans',
  },
  {
    ID: 27,
    Head_ID: 16,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'Project Files',
  },
  {
    ID: 28,
    Head_ID: 17,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'kk',
  },
  {
    ID: 30,
    Head_ID: 18,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'e',
  },
  {
    ID: 31,
    Head_ID: 19,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'd',
  },
  {
    ID: 32,
    Head_ID: 20,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 't',
  },
  {
    ID: 33,
    Head_ID: 21,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'y',
  },
  {
    ID: 34,
    Head_ID: 22,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'u',
  },
  {
    ID: 35,
    Head_ID: 23,
    Full_Name: 'Samantha Bright',
    Prefix: 'Dr.',
    Title: 'z',
  },
]
